# Generated by Django 6.0.2 on 2026-02-22 12:41

import uuid
from django.db import migrations, models


def gen_unique_uuids(apps, schema_editor):
    Server = apps.get_model('dariauth', 'Server')
    for server in Server.objects.all():
        server.api_key = uuid.uuid4()
        server.save(update_fields=['api_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('dariauth', '0001_initial'),
    ]

    operations = [
        # Step 1: Add api_key as nullable, no unique constraint
        migrations.AddField(
            model_name='server',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(gen_unique_uuids, migrations.RunPython.noop),
        # Step 3: Make it non-null and unique
        migrations.AlterField(
            model_name='server',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='NFSShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('server_ip', models.GenericIPAddressField()),
                ('export_path', models.CharField(max_length=512)),
                ('mount_point', models.CharField(max_length=512)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_nfs_shares', to='dariauth.linuxgroup')),
            ],
        ),
    ]
